:sparkles: Add featured blog posts component
dracula/draculatheme.com pull request #167
Opened 2022-04-01 23:29 UTC by luxonauta

2022-04-11 23:08 UTC, zenorocha requested changes
Use 2 column layout

2022-04-13 02:00 UTC, luxonauta commented on components/FeaturedBlogPosts.js
> +    } else if (color === 'pink') {
I made these adjustments! ✨

2022-10-07 15:19 UTC, luxonauta commented
> Use 2 column layout

The adjustments have already been made, Zeno! 🚀

2022-10-11 17:12 UTC, zenorocha requested changes
Make sure the centered container has the same width

2023-01-17 00:39 UTC, merged